name: PrimeFuncPack Core.Unit

on:
  push:
    branches: [ main, dev, feature/*, fix/*, release/* ]

  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Setup dotnet
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: |
          10.0.x
      # dotnet-quality: 'preview' # When using preview versions
        dotnet-quality: 'ga' # General Availability

    # Create Local NuGet Source

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    # Unit

    - name: Restore Solution
      run: dotnet restore ./Unit.slnx

    - name: Build Solution
      run: dotnet build ./Unit.slnx --no-restore -c Release

      # Pack immediately after the build to avoid any potential impact of the tests on the build output
    - name: Pack Unit
      run: dotnet pack ./src/*/*/Unit.csproj --no-build --output ~/nuget -c Release

    - name: Run Unit.Tests.Old
      run: dotnet run --project ./src/*/*/Unit.Tests.Old.csproj --no-build -c Release

    - name: Run Unit.Tests
      run: dotnet run --project ./src/*/*/Unit.Tests.csproj --no-build -c Release

    # Push

    - name: Push Packages
      if: ${{ github.event_name == 'release' }}
      run: >
        dotnet nuget push "../../../nuget/*.nupkg"
        --source https://api.nuget.org/v3/index.json
        --api-key ${{ secrets.NuGetSourcePassword }}
        --skip-duplicate
